begin;
-- Run with: supabase test db (after creating three Auth fixtures in a local stack).
-- These assertions are documented executable probes for the critical policies.
select plan(62);
select has_table('public','games','games exists');
select has_table('public','player_decisions','decisions exist');
select col_is_unique('public','player_decisions',array['turn_id','player_id'],'one decision per player and turn');
select policies_are('public','character_goals',array['goals_read_visible'],'private goal policy exists');
select policies_are('public','player_decisions',array['decisions_insert_own','decisions_read_secret'],'secret decision policies exist');
select function_privs_are('public','complete_turn_resolution',array['uuid','jsonb'],'service_role',array['EXECUTE'],'completion is server-only');
select function_privs_are('public','expire_due_turns',array[]::text[],'service_role',array['EXECUTE'],'timer expiration is server-only');
select function_returns('public','claim_turn_resolution',array['uuid'],'boolean','claim reports lock ownership');
select ok(has_table_privilege('service_role','public.story_turns','SELECT'),'service role reads story turns');
select ok(has_table_privilege('service_role','public.player_decisions','SELECT'),'service role reads decisions');
select ok(has_table_privilege('service_role','public.games','SELECT'),'service role reads games');
select ok(has_table_privilege('service_role','public.world_states','SELECT'),'service role reads world state');
select ok(has_table_privilege('service_role','public.characters','SELECT'),'service role reads characters');
select ok(has_table_privilege('service_role','public.character_goals','SELECT'),'service role reads goals');
select ok(has_table_privilege('service_role','public.memories','SELECT'),'service role reads memories');
select ok(has_table_privilege('service_role','public.narrative_summaries','SELECT'),'service role reads summaries');
select ok(has_table_privilege('service_role','public.story_turns','INSERT') and has_table_privilege('service_role','public.story_turns','UPDATE'),'service role writes story turns');
select ok(has_table_privilege('service_role','public.player_decisions','INSERT') and has_table_privilege('service_role','public.player_decisions','UPDATE'),'service role writes decisions');
select ok(has_table_privilege('service_role','public.memories','INSERT') and has_table_privilege('service_role','public.memories','UPDATE'),'service role writes memories');
select ok(has_table_privilege('service_role','public.games','INSERT') and has_table_privilege('service_role','public.games','UPDATE'),'service role writes games');
select ok(has_table_privilege('service_role','public.audit_events','INSERT') and has_table_privilege('service_role','public.audit_events','UPDATE'),'service role writes audit events');
select ok(not has_table_privilege('service_role','public.audit_events','SELECT'),'service role does not read audit events');
select ok(has_sequence_privilege('service_role','public.audit_events_id_seq','USAGE'),'service role uses audit identity sequence');
select ok(has_sequence_privilege('service_role','public.audit_events_id_seq','SELECT'),'service role reads audit identity sequence state');
select function_privs_are('public','delete_game_for_all',array['uuid'],'authenticated',array['EXECUTE'],'game deletion is exposed only through the authenticated RPC');
select ok(position('auth.uid() is null' in pg_get_functiondef('public.delete_game_for_all(uuid)'::regprocedure))>0,'game deletion rejects unauthenticated callers');
select ok(position('member.player_id = auth.uid()' in pg_get_functiondef('public.delete_game_for_all(uuid)'::regprocedure))>0,'game deletion checks active membership');
select ok(position('for update' in lower(pg_get_functiondef('public.delete_game_for_all(uuid)'::regprocedure)))>0,'game deletion locks concurrent requests');
select ok(position('already_deleted' in pg_get_functiondef('public.delete_game_for_all(uuid)'::regprocedure))>0,'game deletion is safely idempotent');
select ok(position('delete from public.audit_events' in pg_get_functiondef('public.delete_game_for_all(uuid)'::regprocedure))>0,'game deletion clears audit rows explicitly');
select ok(exists(select 1 from pg_constraint where conrelid='public.game_players'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'game players cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.characters'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'characters cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.world_states'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'world state cascades with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.character_goals'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'goals cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.story_turns'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'story turns cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.player_decisions'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'decisions cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.memories'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'memories cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.relationships'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'relationships cascade with games');
select ok(exists(select 1 from pg_constraint where conrelid='public.narrative_summaries'::regclass and confrelid='public.games'::regclass and confdeltype='c'),'summaries cascade with games');
select has_table('public','friend_requests','friend requests exists');
select has_table('public','friendships','friendships exists');
select has_table('public','user_blocks','user blocks exists');
select has_table('public','game_invitations','game invitations exists');
select has_table('public','notifications','notifications exists');
select policies_are('public','friend_requests',array['friend_requests_read_participants'],'friend requests are only directly readable by participants');
select policies_are('public','friendships',array['friendships_read_participants'],'friendships are only directly readable by participants');
select policies_are('public','user_blocks',array['blocks_delete_own','blocks_insert_own','blocks_read_own'],'blocks are owned by blocker');
select policies_are('public','game_invitations',array['game_invitations_read_participants'],'game invitations are only directly readable by participants');
select policies_are('public','notifications',array['notifications_read_own','notifications_update_own_read_state'],'notifications are owned by recipient');
select function_privs_are('public','search_social_profiles',array['text','integer'],'authenticated',array['EXECUTE'],'profile search is exposed through authenticated RPC');
select function_privs_are('public','send_friend_request',array['uuid'],'authenticated',array['EXECUTE'],'friend request sending is exposed through authenticated RPC');
select function_privs_are('public','accept_friend_request',array['uuid'],'authenticated',array['EXECUTE'],'friend request acceptance is exposed through authenticated RPC');
select function_privs_are('public','send_game_invitation',array['uuid','uuid'],'authenticated',array['EXECUTE'],'game invitation sending is exposed through authenticated RPC');
select function_privs_are('public','accept_game_invitation',array['uuid'],'authenticated',array['EXECUTE'],'game invitation acceptance is exposed through authenticated RPC');
select function_privs_are('public','get_my_notifications',array['integer'],'authenticated',array['EXECUTE'],'notification reads are exposed through authenticated RPC');
select ok(position('target_user_id = current_user_id' in pg_get_functiondef('public.send_friend_request(uuid)'::regprocedure))>0,'friend requests reject self-add');
select ok(position('public.is_blocked_between(current_user_id, target_user_id)' in pg_get_functiondef('public.send_friend_request(uuid)'::regprocedure))>0,'friend requests reject blocked interactions');
select ok(position('public.are_friends(current_user_id, target_user_id)' in pg_get_functiondef('public.send_friend_request(uuid)'::regprocedure))>0,'friend requests reject already-friends duplicates');
select ok(position('for update' in lower(pg_get_functiondef('public.accept_game_invitation(uuid)'::regprocedure)))>0,'game invitation acceptance locks pending invitation and game');
select ok(position('active_players >= 2' in pg_get_functiondef('public.send_game_invitation(uuid,uuid)'::regprocedure))>0,'game invitations reject full games');
select ok(position('not public.are_friends(current_user_id, target_user_id)' in pg_get_functiondef('public.send_game_invitation(uuid,uuid)'::regprocedure))>0,'game invitations require friendship');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='game_invitations_pending_game_recipient_unique'),'duplicate pending game invitations are constrained');
select * from finish();
rollback;
