create extension if not exists pgcrypto;
create type public.game_status as enum ('waiting','character_creation','ready','active','paused','completed','abandoned');
create type public.play_mode as enum ('realtime','asynchronous');
create type public.game_phase as enum ('setup','scene','decision','resolution','completed');
create type public.goal_visibility as enum ('public','private','emerging');
create type public.decision_source as enum ('suggested','freeform','timeout');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null check(length(display_name) between 1 and 80), avatar_url text, created_at timestamptz not null default now());
create table public.games (id uuid primary key default gen_random_uuid(), invite_code text not null unique check(invite_code ~ '^[A-Z0-9-]{7,10}$'), owner_id uuid not null references public.profiles(id), title text not null check(length(title)<=160), status game_status not null default 'waiting', play_mode play_mode not null, timer_seconds int check(timer_seconds is null or timer_seconds between 10 and 3600), turn_number int not null default 0 check(turn_number>=0), current_phase game_phase not null default 'setup', invite_expires_at timestamptz, current_turn_deadline timestamptz, resolution_attempts int not null default 0 check(resolution_attempts between 0 and 5), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.game_players (game_id uuid not null references public.games(id) on delete cascade, player_id uuid not null references public.profiles(id) on delete cascade, joined_at timestamptz not null default now(), last_seen_at timestamptz not null default now(), abandoned_at timestamptz, primary key(game_id,player_id));
create table public.characters (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, owner_id uuid not null references public.profiles(id), name text not null check(length(name) between 1 and 80), pronouns text check(length(pronouns)<=80), age_description text check(length(age_description)<=120), appearance text not null check(length(appearance)<=1200), personality_traits jsonb not null default '[]', values_list jsonb not null default '[]', fears jsonb not null default '[]', strengths jsonb not null default '[]', weaknesses jsonb not null default '[]', backstory text not null default '' check(length(backstory)<=4000), freeform_description text not null default '' check(length(freeform_description)<=4000), current_emotional_state jsonb not null default '[]', avatar_url text, is_final boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(game_id,owner_id));
create table public.world_states (game_id uuid primary key references public.games(id) on delete cascade, definition jsonb not null, current_state jsonb not null default '{}', immutable_facts jsonb not null default '[]', updated_at timestamptz not null default now());
create table public.character_goals (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, character_id uuid not null references public.characters(id) on delete cascade, visibility goal_visibility not null, category text not null, description text not null check(length(description)<=1200), status text not null default 'active', progress_summary text check(length(progress_summary)<=1200), created_at timestamptz not null default now());
create table public.story_turns (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, turn_number int not null check(turn_number>0), scene_text text not null check(length(scene_text)<=12000), location text, scene_time text, proposed_intentions jsonb not null default '{}', resolution_text text, resolution_status text not null default 'open' check(resolution_status in ('open','claimed','resolved','failed')), resolution_error text, resolution_claimed_at timestamptz, created_at timestamptz not null default now(), resolved_at timestamptz, unique(game_id,turn_number));
create table public.player_decisions (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, turn_id uuid not null references public.story_turns(id) on delete cascade, player_id uuid not null references public.profiles(id), character_id uuid not null references public.characters(id), source decision_source not null, intention_id text, action_text text not null check(length(action_text) between 1 and 1500), submitted_at timestamptz not null default now(), revealed_at timestamptz, unique(turn_id,player_id));
create table public.memories (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, character_id uuid references public.characters(id) on delete cascade, type text not null, importance smallint not null check(importance between 1 and 10), title text not null check(length(title)<=160), summary text not null check(length(summary)<=1200), involved_entity_ids jsonb not null default '[]', source_turn_id uuid not null references public.story_turns(id), created_at timestamptz not null default now());
create table public.relationships (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, source_character_id uuid not null references public.characters(id), target_character_id uuid not null references public.characters(id), label text not null, trust_description text not null, emotional_state jsonb not null default '[]', unresolved_tensions jsonb not null default '[]', shared_memories jsonb not null default '[]', updated_at timestamptz not null default now(), unique(source_character_id,target_character_id), check(source_character_id<>target_character_id));
create table public.narrative_summaries (id uuid primary key default gen_random_uuid(), game_id uuid not null references public.games(id) on delete cascade, through_turn_number int not null, summary text not null, immutable_facts jsonb not null default '[]', created_at timestamptz not null default now(), unique(game_id,through_turn_number));
create table public.audit_events (id bigint generated always as identity primary key, game_id uuid references public.games(id) on delete set null, actor_id uuid references auth.users(id) on delete set null, event_type text not null, details jsonb not null default '{}', created_at timestamptz not null default now());

create index game_players_player_idx on public.game_players(player_id);
create index characters_game_idx on public.characters(game_id);
create index goals_game_character_idx on public.character_goals(game_id,character_id);
create index turns_game_recent_idx on public.story_turns(game_id,turn_number desc);
create index decisions_turn_idx on public.player_decisions(turn_id);
create index memories_game_importance_idx on public.memories(game_id,importance desc,created_at desc);
create index audit_game_created_idx on public.audit_events(game_id,created_at desc);

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),split_part(new.email,'@',1),'Voyageur')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.add_game_owner_as_player() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.game_players(game_id,player_id) values(new.id,new.owner_id); return new; end $$;
create trigger on_game_created after insert on public.games for each row execute function public.add_game_owner_as_player();

create function public.is_game_member(target_game_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.game_players gp where gp.game_id=target_game_id and gp.player_id=auth.uid() and gp.abandoned_at is null) $$;
create function public.owns_character(target_character_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.characters c where c.id=target_character_id and c.owner_id=auth.uid()) $$;
revoke all on function public.is_game_member(uuid) from public; grant execute on function public.is_game_member(uuid) to authenticated;
revoke all on function public.owns_character(uuid) from public; grant execute on function public.owns_character(uuid) to authenticated;

create function public.join_game_by_code(code text) returns uuid language plpgsql security definer set search_path='' as $$ declare target public.games; begin select * into target from public.games where invite_code=upper(trim(code)) for update; if target.id is null then raise exception 'invalid_code'; end if; if target.status<>'waiting' then raise exception 'game_started'; end if; if target.invite_expires_at is not null and target.invite_expires_at<now() then raise exception 'code_expired'; end if; if exists(select 1 from public.game_players where game_id=target.id and player_id=auth.uid()) then return target.id; end if; if (select count(*) from public.game_players where game_id=target.id and abandoned_at is null)>=2 then raise exception 'game_full'; end if; insert into public.game_players(game_id,player_id) values(target.id,auth.uid()); update public.games set status='character_creation',updated_at=now() where id=target.id and (select count(*) from public.game_players where game_id=target.id and abandoned_at is null)=2; insert into public.audit_events(game_id,actor_id,event_type) values(target.id,auth.uid(),'game.joined'); return target.id; end $$;
revoke all on function public.join_game_by_code(text) from public; grant execute on function public.join_game_by_code(text) to authenticated;

create function public.claim_turn_resolution(target_turn_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare claimed uuid; begin if not exists(select 1 from public.story_turns st where st.id=target_turn_id and public.is_game_member(st.game_id)) then raise exception 'forbidden'; end if; update public.story_turns st set resolution_status='claimed',resolution_claimed_at=now(),resolution_error=null where st.id=target_turn_id and st.resolution_status in ('open','failed') and (select count(*) from public.player_decisions d where d.turn_id=st.id)=2 returning id into claimed; if claimed is not null then update public.player_decisions set revealed_at=now() where turn_id=target_turn_id; end if; return claimed is not null; end $$;
revoke all on function public.claim_turn_resolution(uuid) from public; grant execute on function public.claim_turn_resolution(uuid) to authenticated,service_role;

alter table public.profiles enable row level security; alter table public.games enable row level security; alter table public.game_players enable row level security; alter table public.characters enable row level security; alter table public.world_states enable row level security; alter table public.character_goals enable row level security; alter table public.story_turns enable row level security; alter table public.player_decisions enable row level security; alter table public.memories enable row level security; alter table public.relationships enable row level security; alter table public.narrative_summaries enable row level security; alter table public.audit_events enable row level security;
create policy profiles_read_members on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from public.game_players mine join public.game_players theirs using(game_id) where mine.player_id=auth.uid() and theirs.player_id=profiles.id));
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy games_read_member on public.games for select to authenticated using(public.is_game_member(id));
create policy games_insert_owner on public.games for insert to authenticated with check(owner_id=auth.uid());
create policy games_update_owner on public.games for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy players_read_member on public.game_players for select to authenticated using(public.is_game_member(game_id));
create policy characters_read_member_final on public.characters for select to authenticated using(public.is_game_member(game_id) and (owner_id=auth.uid() or is_final));
create policy characters_write_own on public.characters for all to authenticated using(owner_id=auth.uid() and public.is_game_member(game_id)) with check(owner_id=auth.uid() and public.is_game_member(game_id));
create policy world_read_member on public.world_states for select to authenticated using(public.is_game_member(game_id));
create policy goals_read_visible on public.character_goals for select to authenticated using(public.is_game_member(game_id) and (visibility='public' or public.owns_character(character_id)));
create policy turns_read_member on public.story_turns for select to authenticated using(public.is_game_member(game_id));
create policy decisions_read_secret on public.player_decisions for select to authenticated using(public.is_game_member(game_id) and (player_id=auth.uid() or revealed_at is not null));
create policy decisions_insert_own on public.player_decisions for insert to authenticated with check(player_id=auth.uid() and public.is_game_member(game_id) and public.owns_character(character_id) and revealed_at is null);
create policy memories_read_member on public.memories for select to authenticated using(public.is_game_member(game_id));
create policy relationships_read_member on public.relationships for select to authenticated using(public.is_game_member(game_id));
create policy summaries_read_member on public.narrative_summaries for select to authenticated using(public.is_game_member(game_id));

alter publication supabase_realtime add table public.games,public.game_players,public.characters,public.story_turns,public.player_decisions;
